const books = [
  {
    id: 1,
    title: "React Mastery",
    author: "Dan Abramov",
    image:
      "https://i.pinimg.com/1200x/5b/23/c6/5b23c64f207b675b37293989e8aafa13.jpg",
    description: "A comprehensive guide to mastering React.js.",
    totalAmount: 12,
    borrowed: 5,
    status: "Available",
  },
  {
    id: 2,
    title: "JS Essentials",
    author: "Kyle Simpson",
    image: "https://m.media-amazon.com/images/I/81kqrwS1nNL.jpg",
    description: "Learn the essentials of JavaScript for web development.",
    totalAmount: 8,
    borrowed: 2,
    status: "Available",
  },
  {
    id: 3,
    title: "Python Basics",
    author: "Guido van Rossum",
    image: "https://m.media-amazon.com/images/I/51bRhyVTVGL.jpg",
    description: "Start your Python journey with this beginner-friendly book.",
    totalAmount: 10,
    borrowed: 7,
    status: "Unavailable",
  },
  {
    id: 4,
    title: "Node.js in Action",
    author: "Mike Cantelon",
    image:
      "https://i.pinimg.com/736x/72/c7/e1/72c7e12710d08ef45697cd51aa2068c1.jpg",
    description: "Practical guide to building scalable Node.js applications.",
    totalAmount: 15,
    borrowed: 9,
    status: "Available",
  },
  {
    id: 5,
    title: "CSS Secrets",
    author: "Lea Verou",
    image:
      "https://i.pinimg.com/736x/c0/f8/2c/c0f82ced4ce9ca1baf56eb522c152819.jpg",
    description: "Tips and tricks for mastering CSS.",
    totalAmount: 7,
    borrowed: 3,
    status: "Available",
  },
  {
    id: 6,
    title: "Clean Code",
    author: "Robert C. Martin",
    image: "https://m.media-amazon.com/images/I/41xShlnTZTL.jpg",
    description: "A handbook of agile software craftsmanship.",
    totalAmount: 20,
    borrowed: 12,
    status: "Unavailable",
  },
  {
    id: 7,
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
    description: "Deep dive into JavaScript core mechanisms.",
    totalAmount: 14,
    borrowed: 6,
    status: "Available",
  },
  {
    id: 8,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    image: "https://m.media-amazon.com/images/I/41as+WafrFL.jpg",
    description: "Classic guide for software developers.",
    totalAmount: 18,
    borrowed: 10,
    status: "Available",
  },
  {
    id: 9,
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    image: "https://m.media-amazon.com/images/I/51oXKWrcYYL.jpg",
    description: "Comprehensive textbook on algorithms.",
    totalAmount: 9,
    borrowed: 4,
    status: "Available",
  },
  {
    id: 10,
    title: "Design Patterns",
    author: "Erich Gamma",
    image:
      "https://i.pinimg.com/1200x/da/8d/d4/da8dd4cf60e3a61c41def6ceafe0b873.jpg",
    description: "Elements of reusable object-oriented software.",
    totalAmount: 11,
    borrowed: 5,
    status: "Unavailable",
  },
];

export default books;
